### DISCUSSION TITLE
Can't update site URL

### DISCUSSION THREAD

**Discussion by bsleys** [docker-library/ghost#421] [General]
I figured it out.  After updating the compose.yaml restarting the docker wasn't enough I had to redeploy it.  YA makes total sense I just wasn't thinking.

I'm not sure what I'm doing wrong but no matter what I do I can't get the site URL to update and it continues to point to http://localhost:2368

I've update the URL in the docker compose file but it doesn't change it inside of ghost.  I even tried updating the config.production.json file. Here is my Docker Compose File

```
version: "3.1"
services:
  ghost:
    image: ghost:5-alpine
    restart: always
    ports:
      - 8080:2368
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: <password removed>
      database__connection__database: ghost
      # this url value is just an example, and is likely wrong for your environment!
      url: https://evergreen-longevity.com
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      NODE_ENV: production
    volumes:
      - /data/ghost:/var/lib/ghost/content
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: <password removed>
    volumes:
      - /data/mysql:/var/lib/mysql
networks: {}
```

**Comment by tianon** [comment]
Any clues in your logs?  When I tested just now, I had `INFO Your site is now available on http://the-url-value-i-specified/` in mine.

**Comment by martin-samouiller** [comment]
Hello! 
Did you figure out the issue? I have the same problem

```
blog-lalalala:
    image: ghost:5-alpine
    restart: always
    ports:
      - 8090:2368
    environment:
      database__client: hello
      database__connection__host: dbdb
      database__connection__user: dbadm
      database__connection__password: mypwd
      database__connection__database: ghost
      url: https://mydomain.com
    volumes:
      - ghost-data:/var/lib/ghost/content:rw
    networks:
      - websitenet
    depends_on:
      db:
        condition: service_healthy
```

In the ghost logs I also see:
INFO Your site is now available on https://mydomain.com

But when I connect inside the docker container I see the url: 

```
root@8e6764e1d902:/var/lib/ghost# cat config.production.json 
{
  "url": "http://localhost:2368",
  "server": {
    "port": 2368,
    "host": "::"
  },
  "mail": {
    "transport": "Direct"
  },
  "logging": {
    "transports": [
      "file",
      "stdout"
    ]
  },
  "process": "systemd",
  "paths": {
    "contentPath": "/var/lib/ghost/content"
  }
}
```

**Reply by acburdine** [reply]
@martin-samouiller setting `url` in the environment variables in your docker-compose file doesn't override the value that exists in `config.production.json`. Ghost is configured to ignore the value in `config.production.json` if there is an matching environment variable (see [ghost's configuration docs](https://ghost.org/docs/config/#configuration-options))

**Reply by martin-samouiller** [reply]
Thanks for the clarification! That explains why I saw the following in the logs: 
```INFO Your site is now available on https://mydomain.com/```  

To address my specific need for adding mail information, I updated the `docker-compose.yml` file to override the `config.production.json`. Here's the configuration I used:  

```yaml
blog:
  image: ghost:5.105
  restart: always
  ports:
    - "8090:2368"
  environment:
    database__client: mysql
    database__connection__host: db
    database__connection__user: <user>
    database__connection__password: <password>
    database__connection__database: ghost
    url: https://mydomain.com
  volumes:
    - ghost-data:/var/lib/ghost/content:rw
    - ./config.production.json:/var/lib/ghost/config.production.json
  networks:
    - websitenet
  depends_on:
    db:
      condition: service_healthy
```
