### DISCUSSION TITLE
Docker Compose Installation Issues

### DISCUSSION THREAD

**Discussion by tokenwizard** [docker-library/ghost#422] [General]
I have many other services running in various containers using Compose files. 
I actually have another instance of Ghost running via that same compose file in another server. 

I'm trying to setup another instance of Ghost now, and having issues. IIRC, on the other, working instance, I just copied the `docker-compose.yml` file and modified it to change the server URL to the correct one for my setup and then added a custom password for the MySQL DB and it started up fine. 

For some reason, I am trying this now and it is failing to start. The console output shows an ERRCONNREFUSED error when connecting to MySQL on port 3306. 

I know using the standard docker method, a separate MySQL server needs to be running, but this compose file takes care of the MySQL DB and the Ghost app, right? Am I missing something? 

Here is my `docker-compose.yml` that is failing:
```
services:

  ghost:
    image: ghost:5-alpine
    restart: always
    ports:
      - 8080:2368
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: <<REDACTED>>
      database__connection__database: ghost
      # this url value is just an example, and is likely wrong for your environment!
      url: https://<<REDACTED>>
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      #NODE_ENV: development
    volumes:
      - ghost:/var/lib/ghost/content

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: <<REDACTED>>
    volumes:
      - db:/var/lib/mysql

volumes:
  ghost:
  db:
  ```

I have no other services currently running on this server, so I don't see how there would be any sort of port conflicts. 

Here is the console output when running for the first time. 
```
~/docker compose up

[+] Running 4/4
 ✔ Volume "ghost_db"        Created                                                                                                                                      0.1s 
 ✔ Volume "ghost_ghost"     Created                                                                                                                                      0.0s 
 ✔ Container ghost-ghost-1  Created                                                                                                                                      0.5s 
 ✔ Container ghost-db-1     Created                                                                                                                                      0.5s 
Attaching to db-1, ghost-1
db-1     | 2024-07-03 17:42:31+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.38-1.el9 started.
db-1     | 2024-07-03 17:42:32+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
db-1     | 2024-07-03 17:42:32+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.38-1.el9 started.
db-1     | 2024-07-03 17:42:32+00:00 [Note] [Entrypoint]: Initializing database files
db-1     | 2024-07-03T17:42:32.500382Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
db-1     | 2024-07-03T17:42:32.500577Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 8.0.38) initializing of server in progress as process 80
ghost-1  | [2024-07-03 17:42:33] INFO Ghost is running in production...
ghost-1  | [2024-07-03 17:42:33] INFO Your site is now available on https://<<REDACTED>>/
ghost-1  | [2024-07-03 17:42:33] INFO Ctrl+C to shut down
ghost-1  | [2024-07-03 17:42:33] INFO Ghost server started in 1.38s
ghost-1  | [2024-07-03 17:42:33] ERROR connect ECONNREFUSED 172.18.0.3:3306
ghost-1  | 
ghost-1  | connect ECONNREFUSED 172.18.0.3:3306
ghost-1  | 
ghost-1  | "Unknown database error"
ghost-1  | 
ghost-1  | Error ID:
ghost-1  |     500
ghost-1  | 
ghost-1  | Error Code: 
ghost-1  |     ECONNREFUSED
ghost-1  | 
ghost-1  | ----------------------------------------
ghost-1  | 
ghost-1  | Error: connect ECONNREFUSED 172.18.0.3:3306
ghost-1  |     at /var/lib/ghost/versions/5.87.0/node_modules/knex-migrator/lib/database.js:57:19
ghost-1  |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
ghost-1  | 
ghost-1  | [2024-07-03 17:42:33] WARN Ghost is shutting down
ghost-1  | [2024-07-03 17:42:33] WARN Ghost has shut down
ghost-1  | [2024-07-03 17:42:33] WARN Your site is now offline
ghost-1  | [2024-07-03 17:42:33] WARN Ghost was running for a few seconds
db-1     | 2024-07-03T17:42:33.763875Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
^CGracefully stopping... (press Ctrl+C again to force)
[+] Stopping 2/2
 ✔ Container ghost-ghost-1  Stopped                                                                                                                                      4.6s 
 ✔ Container ghost-db-1     Stopped                                                                                                                                     13.8s 
canceled
```
