### ISSUE TITLE
Question about updates

### ISSUE THREAD

**Issue by laeckerv** [docker-library/ghost#112]
FIrst of all, thank you very much for providing these docker images!

Our docker-compose is configured to use volumes for the files that should ne persistent:

```
    ghost:
        image: ghost:1.12.1
        volumes:
            - blog-apps:/var/lib/ghost/content/apps
            - blog-data:/var/lib/ghost/content/data
            - blog-images:/var/lib/ghost/content/images
            - blog-logs:/var/lib/ghost/content/logs
            - ./htdocs/blog/themes:/var/lib/ghost/content/themes
...
volumes:
    blog-apps:
    blog-data:
    blog-images:
    blog-logs:
```

Now i was wondering if it is safe to simple bump the version of the image to 1.18.2 or even latest, and not having to worry about updates (also future) and the consistency of our data?
