### ISSUE TITLE
Question: Incorrect Mount Point? Use /current/content instead?

### ISSUE THREAD

**Issue by bitbier** [docker-library/ghost#116]
When I went to go and upgrade to the latest Ghost version (tag: 1.19.2), I realized that I ended up losing all of my images that I thought I saved via the volume. The documentation states that the following mount points should be setup as docker volumes:

```
/var/lib/ghost/content
```

However, it looks like this is not the full story. Once you run Ghost and start uploading new images, the images are saved to `/var/lib/ghost/current/content/images` (**NOTE:** `current`) in there. It looks like `.../current/` this is a link to `.../versions/1.19.2/` or vice versa (bash for is not showing links for whatever reason in this container). I was wondering if this is expected? Is it save to just mount against `/var/lib/ghost/current/content/`. I was unsure if the migrator or ghost itself does something dynamic to override that location.

Thanks.

**Comment by tianon** [comment]
Images getting stored under `/current/content` sounds like a bug.

Can you provide us with your `docker run` line or your `docker-compose.yml` file and any applicable additional configuration? (like a Ghost config file, if you've added a custom one)

Any additional information you can provide to help us reproduce the problem would be helpful.

**Comment by bitbier** [comment]
Sure!

This was my first time updating from inside the 1.x.x version space. (`1.5.0-alpine -> 1.19.2-alpine`)

I have the following `docker-compose.yml` file (showing just ghost, I have mysql and nginx in this config as well):

```
version: '2'
volumes:
  ghost_content:
  ...
services:
  ghost:
    image: ghost:1.19.2-alpine
    expose:
      - "2368"
    volumes:
      - ghost_content:/var/lib/ghost/content
    ...
```

With the following overlay for `docker-compose.production.yml`:

```
version: '2'
services:
  ghost:
    volumes:
      - "./ghost/config.production.json:/var/lib/ghost/config.production.json"
...
```

With `config.production.json` being:

```
{
    "url": "...",
    "mail": {
        "transport": "SMTP",
        "options": {
            "service": "Mailgun",
            "auth": {
                "user": "..."
            }
        }
    },
    "database": {
        "client": "mysql",
        "connection": {
            "host": "mysql",
            "user": "...",
            "password": "...",
            "database": "ghost_db",
            "charset": "utf8"
        },
        "debug": false
    },
    "server": {
        "host": "0.0.0.0",
        "port": "2368"
    }
}
```

`...` are redacted users and passwords. I think I've only updated the config file once when I went from `0.11.x -> 1.x.x`.
