### ISSUE TITLE
Update image tag to 1.19 not working.

### ISSUE THREAD

**Issue by jaggerwang** [docker-library/ghost#117]
I changed the image tag in docker compose file to 1(right now it points to 1.19.1), and restart the container, but the version is still 1.10.

```
version: '2'
services:
  ghost:
    image: ghost:1
    environment:
      url: https://blog.jaggerwang.net
    ports:
    - 10100:2368
    volumes:
    - /data/blog/ghost:/var/lib/ghost/content
```

![image](https://user-images.githubusercontent.com/1255011/34762573-2e7f2980-f623-11e7-82eb-1fa09dd6bd03.png)

![image](https://user-images.githubusercontent.com/1255011/34762524-1050ec5a-f623-11e7-933b-eb181e668736.png)
