### ISSUE TITLE
Email service config

### ISSUE THREAD

**Issue by rucuriousyet** [docker-library/ghost#120]
Im not sure how Im supposed to set the configuration file with this image... I need to setup email with mailgun but that doesn't seem to be possible with env vars

**Comment by rucuriousyet** [comment]
Oops.. didn't see #118... I do realize that there is a way to configure mail via env var but I'm not sure if I am supposed to pass a JSON object or some sort of url... Would love to see an example.

**Comment by tianon** [comment]
Yeah, #118 has some good information on it, but also the comment I gave you over in https://github.com/docker-library/ghost/issues/9#issuecomment-358095678:

> combining https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables with https://docs.ghost.org/docs/mail-config#section-mailgun:
> 
> ```bash
> $ docker run ... \
>     -e mail__transport=SMTP \
>     -e mail__options__service=Mailgun \
>     -e mail__options__auth__user=postmaster@example.mailgun.org \
>     -e mail__options__auth_pass=1234567890 \
>     ...
> ```

In the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).

**Comment by davimello28** [comment]
@tianon Does your answer still works? I was trying to use it, but without success :(

I run the container like:

```
docker run -d -p 80:2368 \
-e mail__transport=SMTP \
-e mail__options__service=Mailgun \
-e mail__options__auth__user=postmaster@ ... .mailgun.org \
-e mail__options__auth__pass= ... \
ghost
```

 `docker exec container env` shows that the `env` was correctly there...

![image](https://user-images.githubusercontent.com/3607502/40900819-d32cd454-67a3-11e8-9dfc-adec92815266.png)

..but my `config.production.json` remains with the default values as shown below.

![image](https://user-images.githubusercontent.com/3607502/40900921-4c59e862-67a4-11e8-868d-9d571bfc40a6.png)

I also corrected the missing `_` on `auth__pass` on your previous answer.

PS: I noticed a warning about port 25 traffic. My servers normally run on "paranoid" mode, but I suspect that it has nothing to do with it since the `config.production.json` stays intact. 

Thanks for your time and have a nice day! :)

**Comment by tianon** [comment]
The environment variables take effect directly -- Ghost won't rewrite the configuration file on-disk to reflect their contents.

I don't know if there's a way to ask Ghost for what it believes the current configuration to be -- I'd imagine there probably isn't, since it'd contain passwords, etc so would be privileged content.

**Comment by chovy** [comment]
I can't get this working either with ghost:alpine-2 and docker with mailgun. Nothing works. And when I try to test the email server under Labs, it just sais "server rejected because of error" and nothing useful.

**Comment by AntoinedeChassey** [comment]
Same here.

**Comment by henry74** [comment]
Did you folks try putting the auth user and password values in quotes?

**Comment by AntoinedeChassey** [comment]
Yes, all good now!
I've set it up with Mailgun.
Here is the environment label in my docker-compose:
```yaml
environment:
      url: https://yourdomain.com
      database__client: mysql
      database__connection__host: mariadb
      database__connection__port: 3306
      database__connection__user: dbuser
      database__connection__password: dbpassword
      database__connection__database: db
      mail__transport: SMTP
      mail__from: 'Your name <blog@yourdomain.com>'
      mail__options__service: Mailgun
      mail__options__host: smtp.eu.mailgun.org
      mail__options__port: 587
      mail__options__secureConnection: 'false'
      mail__options__auth__user: 'postmaster@mg.yourdomain.com'
      mail__options__auth__pass: 'passwordFromMailgun'
```
