### ISSUE TITLE
Support docker secrets for setting environment variables

### ISSUE THREAD

**Issue by sjsadowski** [docker-library/ghost#125]
Currently the image supports the following (in the environment stanza):
    
  database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost

It would be useful to take a page from some other official images and allow the following to support using docker secrets:
 
      database__connection__host__file: /path/to/secrets/file_host
      database__connection__user__file:  /path/to/secrets/file_user
      database__connection__password__file:  /path/to/secrets/file_password
      database__connection__database__file:  /path/to/secrets/file_database

Thus requiring minimal changes to the startup process, but then no longer requiring sensitive information being encoded in a compose or stack file.

**Comment by pascalandy** [comment]
That would be nice. Have you seen any docker images supporting this @sjsadowski ?

**Comment by sjsadowski** [comment]
The official wordpress image does @pascalandy

**Comment by tianon** [comment]
The difference there is that the environment variables the `wordpress` image supports are a creation of the image -- they're all read/used within the image's entrypoint script.

The environment variables the `ghost` image supports are a feature of Ghost itself, not something we've set up, so this would likely need to be a feature request for Ghost itself.

**Comment by joeldeteves** [comment]
+1

**Comment by qLb** [comment]
feel free to make PR out of it:

## docker-compose.yml

```
version: '3.4'

services:

  ghost:
    image: ghost:1-alpine
    networks:
      - net
      - backend
    ports:
      - 2368
    volumes:
      - content/themes/casper:/var/lib/ghost/content/themes/casper
      - content/images:/var/lib/ghost/content/images
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      NODE_ENV: production
      url: "https://<fqdn>"
      database__client: mysql
      database__connection__host_FILE: /run/secrets/db.host
      database__connection__user_FILE: /run/secrets/db.user.name
      database__connection__password_FILE: /run/secrets/db.user.pass
      database__connection__database_FILE: /run/secrets/db.name
    secrets:
      - db.host
      - db.user.name
      - db.user.pass
      - db.name
    configs:
      - source: entrypoint
        target: /usr/local/bin/docker-entrypoint.sh
        uid: '0'
        gid: '0'
        mode: 0555
    deploy:
      labels:
        - "APP=GHOST"
      mode: replicated
      replicas: 1
      restart_policy: 
        condition: on-failure
  db:
    image: mariadb:10.1
    networks:
      - backend
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE_FILE: /run/secrets/db.name
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db.root.pass
      MYSQL_USER_FILE: /run/secrets/db.user.name
      MYSQL_PASSWORD_FILE: /run/secrets/db.user.pass
    secrets:
      - db.name
      - db.root.pass
      - db.user.pass
      - db.user.name
    deploy:
      restart_policy: 
        condition: on-failure

  minio:
    image: minio:latest
    ports:
      - 9000
    networks:
      - net
    volumes:
      - content:/export
    secrets:
      - access_key
      - secret_key
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "APP=MINIO"
      restart_policy:
        condition: on-failure

secrets:
  access_key:
    # openssl rand -base64 24 >> .secrets/access_key
    file: .secrets/access_key 
    # or better yet: 
    # openssl rand -base64 24 | docker secret create access_key -
    # external: true
  secret_key:
    file: .secrets/secret_key
  db.host:
    file: .secrets/mysql.host
  db.name:
    file: .secrets/mysql.data.name
  db.root.pass:
    file: .secrets/mysql.root.pass
  db.user.name:
    file: .secrets/mysql.user.name
  db.user.pass:
    file: .secrets/mysql.user.pass

configs:
  entrypoint:
    file: ./entrypoint.sh


volumes:
  mysql_data:
  content:

networks:
  net:
    external: true
  backend:
```

## entrypoint.sh
```
#!/bin/bash
set -euo pipefail

# usage: file_env VAR [DEFAULT]
#    ie: file_env 'XYZ_DB_PASSWORD' 'example'
# (will allow for "$XYZ_DB_PASSWORD_FILE" to fill in the value of
#  "$XYZ_DB_PASSWORD" from a file, especially for Docker's secrets feature)
file_env() {
	local var="$1"
	local fileVar="${var}_FILE"
	local def="${2:-}"
	if [ "${!var:-}" ] && [ "${!fileVar:-}" ]; then
		echo >&2 "error: both $var and $fileVar are set (but are exclusive)"
		exit 1
	fi
	local val="$def"
	if [ "${!var:-}" ]; then
		val="${!var}"
	elif [ "${!fileVar:-}" ]; then
		val="$(< "${!fileVar}")"
	fi
	export "$var"="$val"
	unset "$fileVar"
}

envs=(
	database__connection__host
	database__connection__user
	database__connection__password
	database__connection__database
)

haveConfig=
for e in "${envs[@]}"; do
	file_env "$e"
	if [ -z "$haveConfig" ] && [ -n "${!e}" ]; then
		haveConfig=1
	fi
done

# Default ghost docker-entrypoint.sh

# allow the container to be started with `--user`
if [[ "$*" == node*current/index.js* ]] && [ "$(id -u)" = '0' ]; then
        chown -R node "$GHOST_CONTENT"
        exec su-exec node "$BASH_SOURCE" "$@"
fi

if [[ "$*" == node*current/index.js* ]]; then
        baseDir="$GHOST_INSTALL/content.orig"
        for src in "$baseDir"/*/ "$baseDir"/themes/*; do
                src="${src%/}"
                target="$GHOST_CONTENT/${src#$baseDir/}"
                mkdir -p "$(dirname "$target")"
                if [ ! -e "$target" ]; then
                        tar -cC "$(dirname "$src")" "$(basename "$src")" | tar -xC "$(dirname "$target")"
                fi
        done

        knex-migrator-migrate --init --mgpath "$GHOST_INSTALL/current"
fi

exec "$@"
```
