### ISSUE TITLE
Ghost not upgrading to 2.3.0

### ISSUE THREAD

**Issue by foleman** [docker-library/ghost#161]
If I execute docker-compose pull ghost, it isn't getting the latest version, instead the 2.2.4. 
My docker-compose.yml:

```
ghost:
    image: ghost:2-alpine
    restart: always
    depends_on:
      - "nginx-proxy"
    ports:
      - 127.0.0.1:8080:2368
    volumes:
      - ./data/ghost:/var/lib/ghost/content
    environment:
      - NODE_ENV=development
      - url=https://example.com
      - LETSENCRYPT_EMAIL=blabla@gmail.com
      - LETSENCRYPT_HOST=example.com
      - VIRTUAL_HOST=example.com
```
