### ISSUE TITLE
additional environment vars

### ISSUE THREAD

**Issue by beli3ver** [docker-library/ghost#166]
Hello,

I use ghost with Docker. This is my docker-compose file:
```yaml
version: "3"

services:
  malte-blog:
    image: ghost:latest
    container_name: malte-blog
    restart: always
    environment:
      url: https://example.de
    networks:
      - web
      - internal
    expose:
      - "2368"
    volumes:
      - /srv/malte-blog:/var/lib/ghost/content
    labels:
      - traefik.backend=malteblog
      - traefik.docker.network=web
      - traefik.frontend.rule=Host:example.de
      - traefik.port=2368

networks:
  web:
    external: true
  internal:
    external: false

volumes:
  malte-blog:
```

Everything works perfectly. But, I want to set some additional environment vars like this one:

```json
"privacy": {
    "useTinfoil": true
}
```
Or this one
```json
"mail": {
    "from": "myemail@address.com",
}
```

How can I make this?

**Comment by acburdine** [comment]
@beli3ver see https://docs.ghost.org/concepts/config/#running-ghost-with-config-env-variables - essentially you'd use:

```yml
services:
  malte-blog:
    environment:
      privacy__useTinfoil=true
      mail__from=myemail@address.com
```
