### ISSUE TITLE
Two Instances Problem - impossible create account on second instance.

### ISSUE THREAD

**Issue by gustawdaniel** [docker-library/ghost#172]
I have the following `docker-compose.yml`

```
version: '3.1'

services:

  ghost:
    image: ghost:2-alpine
    restart: always
    ports:
      - ${APP_PORT}:2368
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      - url=${ROOT_URL}
      - database__client=mysql
      - database__connection__host=db
      - database__connection__user=root
      - database__connection__password=example
      - database__connection__database=ghost
      - VIRTUAL_HOST=${DOMAINS}
      - LETSENCRYPT_HOST=${DOMAINS}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
    external: false

networks:
  default:
   external:
     name: ${NETWORK}
```

Where network and variables VIRTUAL_HOST, LETSENCRYPT_HOST, LETSENCRYPT_EMAIL, APP_PORT are connected with using 

> https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion.git 

so you can recreate error with docker compose like this:

```
version: '3.1'

services:

  ghost:
    image: ghost:2-alpine
    restart: always
    ports:
      - ${APP_PORT}:2368
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      - url=${ROOT_URL}
      - database__client=mysql
      - database__connection__host=db
      - database__connection__user=root
      - database__connection__password=example
      - database__connection__database=ghost
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
    external: false
```

And I have two the same files like this on two folders. The only difference is port number and port in ROOT_URL. In both catalogs, I executing command `docker-compose up`.

Both projects starting but I have a probem with the first login. I have a database error.

Let's consider a scenario of sequential executing docker-compose. 

1) In catalog with the name A project starting.
2) I can create an account and my table with users have two users after this: first created by me and second with slug ghost.
3) In catalog B docker-compose up works too.
4) But after going to address /ghost/#/setup/ I can see the error message: "Skip to main content Setup has already been completed.". Sometimes error "No Rows Updated" is obtained. There show many logs but I think it is easy to reproduce.

# Summary

It looks like docker containers interact with each other. How to prevent this and isolate them?
