### ISSUE TITLE
How can I use ghost image to build custom image?

### ISSUE THREAD

**Issue by archervanderwaal** [docker-library/ghost#175]
```Dockfile
FROM ghost:latest

# install mysql-client and git
RUN apt-get update -y --fix-missing && \
    apt-get install git mysql-client  -y && \
    rm -rf /var/lib/apt/lists/*

ADD wait-for-connect.sh /usr/local/bin/wait-for-connect.sh
ADD config.js config.js

# install qn-store plugin
RUN npm install ghost-qn-store && \
    mkdir -p content/adapters/storage && \
    cp -vR node_modules/ghost-qn-store content/adapters/storage/qn-store

# install ghost themes
RUN mkdir -p content/themes && \
    git clone https://github.com/kelyvin/caffeine-theme content/themes/caffeine-theme
```
When I finished , I use command `docker exec -it ghost /bin/bash` but don't have `/var/lib/ghost/content/adapters/storage` in container.

How can I do?

**Comment by archervanderwaal** [comment]
docker-compose.yml

```yml
ghost:
    build: ./ghost
    image: archervanderwaal/ghost-mysql:latest
    container_name: ghost
    volumes:
      - ghost-volume:/var/lib/ghost
    restart: always
    ports:
      - 52057:2368
    environment:
      MYSQL_HOST: "${MYSQL_HOST}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    depends_on:
      - db
    entrypoint: ["docker-entrypoint.sh"]
    command: ["node", "current/index.js"]
```
