### ISSUE TITLE
There is a problem with the config of gmail smtp

### ISSUE THREAD

**Issue by cpfarher** [docker-library/ghost#202]
Failed to send email. Reason: 139832775653184:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332: .

I set by docker-compose this environment variables:
    - mail__transport=SMTP
    - mail__options__host=smtp.gmail.com
    - mail__options__port=587
    - mail__options__secureConnection='false'
    - mail__options__auth__user='myemail@gmail.com'
    - mail__options__auth__password='mypassword'
    - mail__from='foo bar'

I try the above smtp configuration with a chrome extension for send mail with smtp, and all works fine, so, I think there is some problem on SSL3? or anything else?....

**Comment by wglambert** [comment]
Is this the same error you get https://github.com/TryGhost/Ghost/issues/7847

>ERROR: AuthError: Invalid login - 535 Incorrect authentication data

**Comment by cpfarher** [comment]
I do not have two factor authentication enabled on my gmail account. :(. If I enabled two factor authentication, whitch is the format for set the app password on a docker env variable ?

**Comment by wglambert** [comment]
I've been trying to get gmail to work on Ghost, I've done it on redmine before so my email settings allow for SMTP and insecure auth (https://myaccount.google.com/lesssecureapps). 
But every attempt gives me a 500 auth failure

References I was using https://www.reddit.com/r/docker/comments/bnvx8n/trying_to_setup_ghost_with_mailgun/, https://github.com/nodemailer/nodemailer/issues/230, https://github.com/docker-library/ghost/issues/120#issuecomment-549725849 
Also found your forum thread from November https://forum.ghost.org/t/gmail-email-problem-configuration/10421


The error in full:
```console
ghost_1  | [2020-01-09 19:20:34] ERROR "POST /ghost/api/v3/admin/mail/test/" 500 189ms
ghost_1  | 
ghost_1  | Failed to send email. Reason: Authentication required, invalid details provided.
ghost_1  | 
ghost_1  | "Please see https://ghost.org/docs/concepts/config/#mail for instructions on configuring email."
ghost_1  | 
ghost_1  | Error ID:
ghost_1  |     1c3c38e0-3315-11ea-814b-7b1853395a89
ghost_1  | 
ghost_1  | ----------------------------------------
ghost_1  | 
ghost_1  | EmailError: Failed to send email. Reason: Authentication required, invalid details provided.
ghost_1  |     at EmailError.GhostError (/var/lib/ghost/versions/3.2.0/core/server/lib/common/errors.js:10:26)
ghost_1  |     at new EmailError (/var/lib/ghost/versions/3.2.0/core/server/lib/common/errors.js:34:20)
ghost_1  |     at createMailError (/var/lib/ghost/versions/3.2.0/core/server/services/mail/GhostMailer.js:50:12)
ghost_1  |     at transport.sendMail (/var/lib/ghost/versions/3.2.0/core/server/services/mail/GhostMailer.js:92:28)
ghost_1  |     at SMTPTransport.sendMail (/var/lib/ghost/versions/3.2.0/node_modules/nodemailer/lib/engines/smtp.js:124:13)
ghost_1  |     at Transport.sendMailWithTransport (/var/lib/ghost/versions/3.2.0/node_modules/nodemailer/lib/transport.js:80:20)
ghost_1  |     at Nodemailer.sendMail (/var/lib/ghost/versions/3.2.0/node_modules/nodemailer/lib/nodemailer.js:209:20)
ghost_1  |     at /var/lib/ghost/versions/3.2.0/node_modules/nodemailer/lib/nodemailer.js:68:20
ghost_1  |     at /var/lib/ghost/versions/3.2.0/node_modules/nodemailer/lib/nodemailer.js:195:9
ghost_1  |     at process._tickCallback (internal/process/next_tick.js:61:11)
ghost_1  | 
ghost_1  | Error: Authentication required, invalid details provided
ghost_1  |     at SMTPTransport.sendMail (/var/lib/ghost/versions/3.2.0/node_modules/nodemailer/lib/engines/smtp.js:124:22)
ghost_1  |     at Transport.sendMailWithTransport (/var/lib/ghost/versions/3.2.0/node_modules/nodemailer/lib/transport.js:80:20)
ghost_1  |     at Nodemailer.sendMail (/var/lib/ghost/versions/3.2.0/node_modules/nodemailer/lib/nodemailer.js:209:20)
ghost_1  |     at /var/lib/ghost/versions/3.2.0/node_modules/nodemailer/lib/nodemailer.js:68:20
ghost_1  |     at /var/lib/ghost/versions/3.2.0/node_modules/nodemailer/lib/nodemailer.js:195:9
ghost_1  |     at process._tickCallback (internal/process/next_tick.js:61:11)
```

This is the current docker-compose file, I tried it with secrets and using different config options

<details>
<summary> docker-compose.yml </summary>

```yaml
version: '3.1'
  
services:

  ghost:
    image: ghost
    restart: always
    ports:
      - 8080:2368
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      database__client: mysql
      database__connection__host: db
      database__connection__port: 3306
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
      mail__transport: SMTP
      mail__options__host: smtp.gmail.com
      mail__options__service: Gmail
      mail__options__secureConnection: 'false'
      mail__options__port: 587
      mail__options__auth__user: "[user@gmail.com]"
      mail__options__auth__password: "[pass]"
      #      mail__options__auth__user: /run/secrets/email
      #      mail__options__auth__password: /run/secrets/email_password
    secrets:
      - email
      - email_password

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

secrets:
  email:
    file: email.txt
  email_password:
    file: email_password.txt
```

</details>

---

However using a custom config from https://ghost.org/docs/concepts/config/#mail works
It's the provided `config.development.json` with the `mail` section modified. The other values get overridden by environment variables (As the mail section should have)

<details>
<summary> config.development.json </summary>

```json
{
  "url": "http://localhost:2368",
  "server": {
    "port": 2368,
    "host": "0.0.0.0"
  },
  "database": {
    "client": "sqlite3",
    "connection": {
      "filename": "/var/lib/ghost/content/data/ghost.db"
    }
  },
  "mail": {
    "transport": "SMTP",
    "options": {
        "service": "Gmail",
        "auth": {
            "user": "[email]",
            "pass": "[pass]"
        }
    }
},
  "logging": {
    "transports": [
      "file",
      "stdout"
    ]
  },
  "process": "systemd",
  "paths": {
    "contentPath": "/var/lib/ghost/content"
  }
}
```

</details>

Using this docker-compose file

<details>
<summary> docker-compose.yml </summary>

```yaml
version: '3.1'
  
services:

  ghost:
    image: ghost
    restart: always
    ports:
      - 8080:2368
    volumes:
      - ./config.production.json:/var/lib/ghost/config.production.json
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      database__client: mysql
      database__connection__host: db
      database__connection__port: 3306
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
```

</details>


The test email I received
![image](https://user-images.githubusercontent.com/26428991/72100924-63635380-32d8-11ea-8e79-ac53b7ccfe9d.png)

**Comment by wglambert** [comment]
Found the error, `mail__options__auth__password` should be `mail__options__auth__pass`

docker-compose file that works
```yaml
version: '3.1'
  
services:

  ghost:
    image: ghost
    restart: always
    ports:
      - 8080:2368
    environment:
      # see https://docs.ghost.org/docs/config#section-running-ghost-with-config-env-variables
      database__client: mysql
      database__connection__host: db
      database__connection__port: 3306
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
      mail__transport: SMTP
      mail__options__service: Gmail
      mail__options__auth__user: "[email"
      mail__options__auth__pass: "[pass]"

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
```
