### ISSUE TITLE
Failed to send email; "invalid" details provided

### ISSUE THREAD

**Issue by noahsbwilliams** [docker-library/ghost#214]
Hi folks,

I've come across an issue with SMTP credentials being rejected as invalid. I've now tried this with two different providers, just to make sure it isn't specific to one of them.

When I go to send a test email in the Ghost admin interface, I get this message:

> Failed to send email. Reason: Authentication required, invalid details provided.

Below is the environment section of my docker-compose file:

Config for Mailgun:

```
environment:
      database__client: 'sqlite3'
      url: 'https://domain.com'
      mail__transport: 'SMTP'
      mail__options__service: 'Mailgun'
      mail__options__host: 'smtp.mailgun.org'
      mail__options__port: '587'
      mail__options__secureConnection: 'true'
      mail__options__auth__user: 'postmaster@email.domain.com'
      mail__options__auth__password: ${MAILGUN_PW}
```

Config for Sendgrid:

```
environment:
      database__client: 'sqlite3'
      url: 'https://domain.com'
      mail__transport: 'SMTP'
      mail__options__service: 'Sendgrid'
      mail__options__port: '587'
      mail__options__secureConnection: 'true'
      mail__options__host: 'smtp.sendgrid.net'
      mail__options__auth__user: 'apikey'
      mail__options__auth__password: ${SENDGRID_PW}
```

Note: I have placed a `.env` file with the `MAILGUN_PW`/`SENDGRID_PW` variables in the working dir. I also verified that the variables are making their way into the containers by running:

`docker exec <containerhash> printenv`

Additional troubleshooting steps:

- [x] Hardcoding password into the docker-compose
- [x] Removed the quotes
- [x] Using port 465 instead of 587
- [x] Trying secureConnection and non-secureConnection configurations
- [x] Trying different API keys
  - [x] Checking permissions on existing API keys

Additional ridiculous troubleshooting steps:
- [x] Explicitly opened port 587 for outgoing traffic on the docker host
  - [x] Explicitly opened port 587 on the ghost container

Log data:

[email_failure.log](https://github.com/docker-library/ghost/files/4237980/email_failure.log)
