### ISSUE TITLE
Editing current theme

### ISSUE THREAD

**Issue by AlexKalopsia** [docker-library/ghost#219]
Hi everyone,

I am a bit confused as to how I am supposed to do some edits to my current theme. Even though I mounted `/content`, there are no files within the `/themes` folder.

What am I missing?

**Comment by pascalandy** [comment]
Hi,
This is not related to this docker image.

But let me try to help. You have to download the theme. Then, you must update it (it uses Handle Bar).

See https://ghost.org/docs/api/v3/handlebars-themes/
You can also ask for help on https://forum.ghost.org/c/help/6

Cheers!

**Comment by lapphan** [comment]
@AlexKalopsia please provide your `docker-compose.yml`.

**Comment by pascalandy** [comment]
Because editing your theme, you should be able to run ghost and upload theme via the GUI in the admin panel.

**Comment by kopax** [comment]
I have issue when starting the container, I can't work on the theme in intellij due to permissions access, the uid guid used are 1000, there's no way to change that, my user is another uid guid

**Comment by pascalandy** [comment]
Can't help without details

> I have issue when starting the container, I can't work on the theme in intellij due to permissions access, the uid guid used are 1000, there's no way to change that, my user is another uid guid

**Comment by 1player** [comment]
The problem is that this image nukes the permissions with its `tar` in `docker-entrypoint.sh` for some reason, which is incompatible with many setup and/or rootless containers.

I'm trying to set this up using Kubernetes, and I would like to develop my theme locally. If I mount from "./themes" to "/var/lib/ghost/content/themes", three things might happen:

* On a regular Docker setup, iff your host uid == 1000 (like the node user on the Docker image), everything is fine.
* On a regular Docker setup, if you host uid != 1000, like @kopax has, the entrypoint will nuke your permissions with its tar, so you won't be able to edit the theme files locally (because they're not owned by your uid anymore)
* On a rootless Podman setup, as recommended nowadays, the node container user with uid 1000 is mapped to host uid 10099, so it's basically like case 2, where as soon as the container starts your permissions get nuked.

The entrypoint script should not chown nor change any permission of its files, as it works only on a small percentage of setups, and it's a nightmare on others.

**Comment by tianon** [comment]
For production setups, it's definitely useful, but I agree it's less than ideal for development workflows (the `worpdress` image has struggled with this a _lot_).

What I'd suggest here is to use a non-root user for the container, which will bypass the `chown` behavior entirely (`docker run --user 1000 ...`).

**Comment by 1player** [comment]
> What I'd suggest here is to use a non-root user for the container, which will bypass the `chown` behavior entirely (`docker run --user 1000 ...`).

Not really, the `tar` command will try to write to `/var/lib/ghost` and subdirectories, and if you have a bound volume there (i.e. your theme, which should be perfectly fine if it's read only), the image won't start because tar fails.

**Comment by jalberto** [comment]
To change file permission is very intrusive, I understand the need for something like this a couple of years ago, but now both in production (k8s has a way to define which permissions should be used to mount a volume) and dev (rootless) is a pain

**Comment by jalberto** [comment]
My workaround:

```
    user: root
    entrypoint: ["node", "current/index.js"]
```

this works fine with podman rootless

**Comment by derek-adair** [comment]
Ok, I have figured out a config that will support my desired worklow with the supplied official compose file.

The trick was to mount my theme in the compose file directly to the theme directory;

```
volumes:
  - /path/to/theme:/var/lib/content/themes/theme-name
```

This theme will not show up in the list of themese and you must click "advanced" to select it.

**Comment by derek-adair** [comment]
Update: It was a more ideal setup to just add a volume(s) to the given docker-compose

```
version: '3.1'
services:

  ghost:
    image: ghost:5-alpine
    restart: always
    volumes:
      - ./content:/var/lib/ghost/content
    ports:
      - 8080:2368
    environment:
     # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
      # this url value is just an example, and is likely wrong for your environment!
      url: http://localhost:8080
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      #NODE_ENV: development

  db: 
    image: mysql:8.0
    restart: always
    volumes:
        - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
```

Then you can just clone into your theme in the theme directory. It should be noted that;

1. run `yarn install && yarn run dev` to see live css changes
2. .hbs do not reload for some reason (even in development) - workaround for now is to switch themes back and forth.
