### ISSUE TITLE
No images in AMP pages except featured images

### ISSUE THREAD

**Issue by MoryCorp** [docker-library/ghost#223]
Hi,

First of all, here is a sample page of the problem I'm facing : https://holory.fr/ghostboard-google-analytics/amp/

The generated AMP pages do not display the images contained in the blog posts except featured image.

Current version : 3.14.0
Image: Ghost-alpine

Using Traefik 1.7 as reverse-proxy.

Here's the docker-compose for Ghost : 

```
version: '2'
services:
  server:
    image: ghost:alpine
    container_name: ghost
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:blog.example.com"
      - "traefik.port=2368"
      - "traefik.docker.network=web"
    volumes:
      - /opt/ghost/blog:/var/lib/ghost/content
    environment:
      - NODE_ENV=production
      - url=https://blog.example.com

networks:
  web:
    external: true
```

Traefik TOML:

```
debug = false

defaultEntryPoints = ["https","http"]

# The syntax is somewhat esoteric IMHO so this is mostly copy-paste
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "traefik.example.com"
watch = true
exposedbydefault = false

[acme]
email = "youremail@example.com"
storage = "acme.json"
entryPoint = "https"
OnHostRule = true
[acme.httpChallenge]
entryPoint = "http"

# Enable web configuration backend
[web]

# Web administration
```

And traefik docker-compose :

```
version: '2'

services:
  proxy:
    # Always use a proper version! (edited)
    image: traefik:v1.6.6-alpine
    # Feel free to change the loglevel if needed
    command: --web --docker --logLevel=INFO
    restart: unless-stopped
    # Here's the network we created
    networks:
      - web
    # The traefik entryPoints
    ports:
      - "80:80"
      - "443:443"
    labels:
      # Make sure this domain points to your IP so that traefik can request a cert
      - "traefik.frontend.rule=Host:traefik.example.com"
      # Traefik will proxy to its own GUI
      - "traefik.port=8080" 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/traefik/traefik.toml:/traefik.toml
      - /opt/traefik/acme.json:/acme.json
networks:
  web:
    external: true
```

Any help would be appreciated
