### ISSUE TITLE
docker-compose

### ISSUE THREAD

**Issue by standbyoneself** [docker-library/ghost#224]
I have tried do dockerize my ghost website.
Here is docker-compose.yaml:

    version: '3.1'
    
    services:
      ghost:
        container_name: ghost
        image: ghost:3-alpine
        restart: always
        ports:
          - 2368:2368
        environment:
          - NODE_ENV=development
        volumes:
          - ./content:/var/lib/ghost/content
          - ./config.development.json:/var/lib/ghost/config.development.json

And there is my config.development.json (no need in production now):

    {
      "url": "http://localhost:2368/",
      "server": {
        "port": 2368,
        "host": "127.0.0.1"
      },
      "database": {
        "client": "sqlite3",
        "connection": {
          "filename": "/content/data/ghost-local.db"
        }
      },
      "mail": {
        "transport": "Direct"
      },
      "logging": {
        "transports": ["file", "stdout"]
      },
      "process": "local",
      "paths": {
        "contentPath": "/content"
      }
    }

When I run `docker-compose up`, logs contain output:

    MacBook-Air-mas:greenpl-landing-ghost boss$ docker-compose up
    Creating network "greenpl-landing-ghost_default" with the default driver
    Creating ghost ... done
    Attaching to ghost
    ghost    | chown: /var/lib/ghost/content/themes/casper: No such file or directory

What's wrong?

P. S. My file structure is below:
[enter image description here][1]

  [1]: https://i.stack.imgur.com/AvhEc.png

**Comment by pascalandy** [comment]
You can't use relative path. Always use an absolute path. 

```
    volumes:
      - ./content:/var/lib/ghost/content
      - ./config.development.json:/var/lib/ghost/config.development.json
```

You can try this https://github.com/firepress-org/ghostfire#option-3-stateful-with-configs, then adapt it to your compose set up ;-)

**Comment by standbyoneself** [comment]
It didn't help.
Changed docker-compose:
```
version: '3.1'

services:
  ghost:
    container_name: ghost
    image: ghost:3-alpine
    restart: always
    ports:
      - 2368:2368
    volumes:
      - /Users/boss/Desktop/greenpl-landing-ghost/content:/var/lib/ghost/content
      - /Users/boss/Desktop/greenpl-landing-ghost/config.production.json:/var/lib/ghost/config.production.json
```
Also tried ${PWD} instead of absolute path.

config.production.json (now in production):
```
{
  "url": "http://localhost:2368/",
  "server": {
    "port": 2368,
    "host": "127.0.0.1"
  },
  "database": {
    "client": "sqlite3",
    "connection": {
      "filename": "/var/lib/ghost/content/data/ghost-local.db"
    }
  },
  "mail": {
    "transport": "Direct"
  },
  "logging": {
    "transports": ["file", "stdout"]
  },
  "process": "local",
  "paths": {
    "contentPath": "/var/lib/ghost/content"
  }
}
```

Any thoughts?
