### ISSUE TITLE
 '/var/lib/ghost/content': Permission denied

### ISSUE THREAD

**Issue by andreborud** [docker-library/ghost#225]
When trying to run ghost with docker compose I get the following error:

```
2020-06-25T20:59:41.481429000Z find: '/var/lib/ghost/content': Permission denied
2020-06-25T20:59:41.482828000Z chown: changing ownership of '/var/lib/ghost/content': Permission denied
```

I have setup my docker compose file to point /var/lib/ghost/content to another dir. This is the docker compose file:

```
version: "3.7"
services:
  blog:
    image: ghost:latest
    container_name: blog_com
    restart: always
    depends_on:
      - blog_db
    ports:
      - "2370:2368"
    environment:
      url: https://blog.com
      preloadHeaders: 100
      database__client: mysql
      database__connection__host: blog_db
      database__connection__user: blog
      database__connection__password: password
      database__connection__database: blog
      database__connection__port: 3308
    volumes:
      - /opt/blog_content:/var/lib/ghost/content
    networks:
      - proxy-net

  blog_db:
    image: mysql:8.0
    restart: always
    container_name: blog_mysql
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_USER: blog
        MYSQL_PASSWORD: password
        MYSQL_DATABASE: blog
        MYSQL_TCP_PORT: 3308
    volumes:
      - /opt/blog_mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3308:3308
    networks:
      - proxy-net

networks:
  proxy-net:
    external:
      name: blog_network
```

I'm doing similarly for the mysql dir which works fine and sets itself up perfectly before starting ghost. 

Doing `ls -l` in `/opt/` looks like this: 

```
drwxr-xr-x. 2 root    root    6 Jun 25 20:42 blog_content
drwxr-xr-x. 7 polkitd root 4096 Jun 25 20:53 blog_mysql
```

I'm running the docker-compose file on the latest version of Fedora CoreOS. Starting it with the usual `sudo docker-compose up -d`. What could be causing this?
