### ISSUE TITLE
Problem installing Ghost with docker-compose 

### ISSUE THREAD

**Issue by Encang-Cutbray** [docker-library/ghost#232]
Hai, i have a problem to install ghost with docker-compose 
the problem is 
`ERROR ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client`
`ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client`
`"Unknown database error"`
`Error ID:`
    `500`
`Error Code: `
    `ER_NOT_SUPPORTED_AUTH_MODE`

my docker-compose 

version: "3.1"
services:
  ghost:
    image: ghost:latest
    restart: always
    networks:
      - ghost-lover
    ports:
      - 8080:2368
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
      url: http://localhost:8080

  db:
    image: mysql:latest
    networks:
      - ghost-lover
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - mysql-lover:/var/lib/mysql

volumes:
  mysql-lover:
networks:
  ghost-lover:

can do you help me? thank

**Comment by acburdine** [comment]
@Encang-Cutbray the reason this is occurring I think is because `mysql:latest` installs MySQL version 8, which currently has a couple of [known incompatibilities](https://github.com/mysqljs/mysql/pull/2233) with the nodejs MySQL driver.

To fix this, try updating your `db` image to `mysql:5.7` instead.

**Comment by Encang-Cutbray** [comment]
@acburdine yes, I used `mysql:latest` for my database, and i changed to `mysql:5.7`, it is working now, thanks for information about `known incompatibilities mysql 8.0` thank very much

**Comment by heng1025** [comment]
@acburdine ghost 4+ has supported mysql 8.0，maybe you need open `mysql_native_password`.
Here is the example：
- Run a container independently
`docker run --name db -e MYSQL_ROOT_PASSWORD=example  -d mysql --default-authentication-plugin=mysql_native_password`

- docker-compose.yml
```
version: '3.8'
services:
  ghost:
    image: ghost:alpine
    restart: always
    ports:
      - 8080:2368
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
      # this url value is just an example, and is likely wrong for your environment!
      url: http://localhost:8080
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      #NODE_ENV: development

  db:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
```

**Comment by dnsmichi** [comment]
@heng1025 Thanks a lot for sharing, it helped my upgrade to v4 and MySQL 8 :-) 

I've created a summary blog for everyone looking into the same: https://dnsmichi.at/2021/11/30/upgrade-to-ghost-v4-with-docker-compose/

**Comment by robetus** [comment]
> @acburdine yes, I used `mysql:latest` for my database, and i changed to `mysql:5.7`, it is working now, thanks for information about `known incompatibilities mysql 8.0` thank you very much

Don't know why it shows 8.0 in the official docs when it 8.0 doesn't work. Same exact issue, worked totally fine with 5.7.

**Comment by tianon** [comment]
Namely because anything older than MySQL 8.0 is end of life (5.7 is no longer supported).

I've just tested, and it worked totally fine for me with `mysql:8.0`, but maybe I have to do something specific to encourage it to fail?

```yaml
version: '3.1'

services:

  ghost:
    image: ghost:5-alpine
    restart: always
    ports:
      - 2368:2368
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
      # this url value is just an example, and is likely wrong for your environment!
      url: http://my-local-system-hostname:2368
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      #NODE_ENV: development
    volumes:
      - ghost:/var/lib/ghost/content

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db:/var/lib/mysql

volumes:
  ghost:
  db:
```

(only changed port mapping and `url` value from the example on Docker Hub)
