### ISSUE TITLE
Mouting /var/lib/ghost copy folders from content/ to / of project

### ISSUE THREAD

**Issue by cescoferraro** [docker-library/ghost#25]
docker-compose.yml

``` yml
ghost:
  image: ghost
  ports:
    - 2368:2368
  environment:
    - NODE_ENV=production
  volumes:
      - ${PWD}:/var/lib/ghost
  ports:
    - "2368:2368"
```

Why does it copy the folders to the root of the project? I wish I could mount the content folder and the config.js files seperatly.

![screen shot 2015-12-15 at 12 52 44 am](https://cloud.githubusercontent.com/assets/6259987/11800827/4211d670-a2c7-11e5-89df-14b1776e3767.png)
