### ISSUE TITLE
Docker Compose for SMTP setup not working.

### ISSUE THREAD

**Issue by MerNat** [docker-library/ghost#265]
I'm trying to use SendGrid SMTP service and thus my Ghost app from my docker-compose file looks like given below:
```
ghost:
    image: ghost:alpine
    networks:
      - traefik-network
    volumes:
      - type: volume
        source: ghost-data
        target: /var/lib/ghost/content
    deploy:
      replicas: 1
      labels:
        - traefik.frontend.rule=Host:example.com, www.example.com
        - traefik.enable=true
        - traefik.port=2368
        - traefik.tags=traefik-network
        - traefik.docker.network=traefik-network
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        - traefik.webservice.frontend.entryPoints=https
    environment:
      - url=https://example.com/
      - database__client=mysql
      - database__connection__host=master_db
      - database__connection__user=ghostuser
      - database__connection__password=password
      - database__connection__database=ghostdb
      - mail__transport=SMTP
      - mail__from='UserName <email@gmail.com>'
      - mail__options__service=Sendgrid
      - mail__options__host=smtp.sendgrid.net
      - mail__options__port=587
      - mail__options__secureConnection=false
      - mail__options__auth__user=apikey
      - mail__options__auth__password=myapikey
      - VIRTUAL_HOST=0.0.0.0:8080
      - VIRTUAL_PORT=2368
    depends_on:
      - master_db
```

Everything is working great except that when I checked the config.production.json and or config.development.json config files in the running container, the mail config part still remains like this:

```
{
  "url": "http://localhost:2368",
  "server": {
    "port": 2368,
    "host": "0.0.0.0"
  },
  "database": {
    "client": "sqlite3",
    "connection": {
      "filename": "/var/lib/ghost/content/data/ghost.db"
    }
  },
  "mail": {
    "transport": "Direct"
  },
  "logging": {
    "transports": [
      "file",
      "stdout"
    ]
  },
  "process": "systemd",
  "paths": {
    "contentPath": "/var/lib/ghost/content"
  }
}

```
Docker image is not even picking up the config for the SMTP configuration.
