### ISSUE TITLE
can't get my docker image up and running

### ISSUE THREAD

**Issue by fahadshery** [docker-library/ghost#274]
Hi,

I am getting a permission error and I am not sure why because I do have the appropriate access to the server.

Here is my docker config:
```
ghost:
    image: ghost
    restart: always
    ports:
      - 8080:2368
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: localhost:31200
      database__connection__user: ghost
      database__connection__password: example
      database__connection__database: ghost
      # this url value is just an example, and is likely wrong for your environment!
      url: http://localhost:8080
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      #NODE_ENV: development
   volumes:
      - /path/to/ghost/blog:/var/lib/ghost/content
```

I am getting this error:
```
tar: casper: Cannot create symlink to '/var/lib/ghost/current/content/themes/casper': Operation not supported
Thu, Nov 25 2021 2:52:54 pm | tar: Exiting with failure status due to previous errors
```

what am I doing wrong?
