### ISSUE TITLE
.snapshot directory is 'read only'

### ISSUE THREAD

**Issue by Bugs5382** [docker-library/ghost#287]
I keep deploying this docker with the k8-home ghost helm chart... and I keep getting this:

```
chown: changing ownership of '/var/lib/ghost/content/.snapshot': Read-only file system
chown: changing ownership of '/var/lib/ghost/content/.snapshot': Read-only file system
chown: changing ownership of '/var/lib/ghost/content/.snapshot': Read-only file system
chown: changing ownership of '/var/lib/ghost/content/.snapshot': Read-only file system
chown: changing ownership of '/var/lib/ghost/content/.snapshot': Read-only file system
```

I been looking at this for a few days and I am stuck.

Here is the "helm" chart values I submit:

```
#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: ghost
  # -- image tag
  tag: 4.27.2
  # -- image pull policy
  pullPolicy: IfNotPresent

# See https://ghost.org/docs/config/#running-ghost-with-config-env-variables
env:
  url: "https://<EXCLUDED>/"
  database__client: mysql
  database__connection__host: <EXCLUDED>
  database__connection__user: ghost-965
  database__connection__password:  <EXCLUDED>
  database__connection__database: <EXCLUDED>
  NODE_ENV: production

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 2368

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  content:
    enabled: true
    accessMode: ReadWriteMany
    storageClass: netapp-a-nfs-client
    size: 1Gi
    mountPath: /var/lib/ghost/content

mariadb:
  enabled: false

```

I don't think this is a kube error, but a docker image error. Thanks.
