### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by ErisDS** [docker-library/ghost#309]
With the release of Ghost v5 we have spent quite a lot of time carefully crafting update docs

https://ghost.org/docs/update

However, they are for the recommended install method which is Ghost CLI, and which we use to do a lot of the legwork and prevent issues.

With docker, not sure there's any way we can do anything to prevent people updating incorrectly, but it seems there should probably be detailed update docs.

The critical details being:

1. mysql8 is now the only supported database in production. 
2. updates across majors are only guaranteed to work if you update to the latest version in your major first.

To clarify that last point, if you're on 3.25.9, you need to update Ghost to 3.42.9 - including starting the server to trigger the migrations - _before_ updating to v5.0.0. 

Note: you don't have to cycle through every major - you don't have to upgrade to v4 first. 

There's absolutely no way to guarantee you can update from any version to any version without data loss or corruption as there can always be bugs that are fixed in later versions 🤷‍♀️

**Comment by tianon** [comment]
Yeah, this type of upgrade is a little bit complicated all around :grimacing:

I think the best I can suggest is maybe a little blurb added to the very top of https://github.com/docker-library/docs/blob/master/ghost/content.md (maybe moving up the existing "Upgrading Ghost" section)?

Does it already / do you think it would be possible/reasonable to have the newer versions balk with a useful error message on startup/migration if you _haven't_ done this, perhaps linking to those docs? :sweat_smile:

**Comment by BlueHatbRit** [comment]
I've just completed two docker based ghost upgrades and it was flawless. I thought I'd note down my approach for anyone who might find it useful, I'm not sure how useful it'll be for the future documentation proposed but maybe it'll help a little.

I'm using docker-compose for them both so here's the steps I went through.

1. Take a backup of the site in question first. For me it was enough to just get a json export dump which I've happily restored from in the past.
2. Update the MySQL container to `mysql:8.0.29`, if you're using a different flavour YMMV. I did a full restart using `docker-compose down && docker-compose up -d && docker-compose logs -f` to allow the DB to come up from 5.x to 8 and then did a quick test that everything was still ok.
3. Update to the top version of the major I was on. For me this was a case of going from `4.44-alpine` to `4.48-alpine`. Same deal command as above to do a full restart and another quick manual test.
4. Update to `ghost:5.0.2-alpine`, another full restart using the docker-compose command above followed by another manual test.

This process worked for me with the various container versions above for two seperate sites on a dedicated `Ubuntu 21.10 (GNU/Linux 5.13.0-41-generic x86_64)` machine.

My final docker-compose file for both sites is:

```
version: '3.7'

services:

  ghost:
    image: ghost:5.0.2-alpine
    restart: always
    depends_on:
      - db
    ports:
      - "127.0.0.1:3400:2368"
    volumes:
      - ./content:/var/lib/ghost/content
      - ./config.json:/var/lib/ghost/config.production.json
    env_file:
      - ./db.env

  db:
    image: mysql:8.0.29
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    env_file:
      - ./db.env
```

(This fits my needs, other people may need your volumes done slightly differently).

Hopefully this helps in someway!
