### ISSUE TITLE
Incorrect MySQL configuration in the Docker Compose example

### ISSUE THREAD

**Issue by y-liang** [docker-library/ghost#324]
In the docker compose section on the official image. It shows the database config as follows.
```
 environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
```
Anyone (that didn't click that ghost docs link and mindlessly) followed that config would get an error when building the container, due to an invalid database host. The database config [on the ghost docs](https://ghost.org/docs/config/#configuration-options) suggests this.
```
"database": {
  "client": "mysql",
  "connection": {
    "host": "127.0.0.1",
    "port": 3306,
    "user": "your_database_user",
    "password": "your_database_password",
    "database": "your_database_name"
  }
}
```
So the database config in the docker compose example should be corrected to this instead, even if it's just for demonstation. And not to mention that 'MySQL 8 will be the required database in the next major release of Ghost.'
```
 environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: localhost
      database__connection__user: root
      database__connection__password: example
      database__connection__database: db
```
