### ISSUE TITLE
Use existing DB Host

### ISSUE THREAD

**Issue by imp1sh** [docker-library/ghost#330]
Hi,

I'm not sure if this is a missing feature, a bug or if I'm just being stupid.
Yet I cannot find a hint in the documentation about my case.

I don't want to have a mysql docker container, but I just want ghost connecting to a specific db hostname I give.
How to do this? Hope this is even possible.

ty

**Comment by wglambert** [comment]
The env vars in the example `docker-compose.yml` work for a database whether it's in a container or not https://github.com/docker-library/docs/tree/master/ghost#-via-docker-stack-deploy-or-docker-compose

Just remove the separate `db` service at the bottom

**Comment by imp1sh** [comment]
That's what I tried at first, but I get this error:
```
dockerrx1:~/ghost_libcom# docker-compose up
WARNING: Found orphan containers (ghost_libcom_ghost_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Creating ghost_libcom_ghostlibcom_1 ... done
Attaching to ghost_libcom_ghostlibcom_1
ghostlibcom_1  | [2022-08-19 16:32:44] INFO Ghost is running in production...
ghostlibcom_1  | [2022-08-19 16:32:44] INFO Your site is now available on https://www.libcom.de/
ghostlibcom_1  | [2022-08-19 16:32:44] INFO Ctrl+C to shut down
ghostlibcom_1  | [2022-08-19 16:32:44] INFO Ghost server started in 0.341s
ghostlibcom_1  | [2022-08-19 16:32:44] ERROR Invalid database host.
ghostlibcom_1  |
ghostlibcom_1  | Invalid database host.
ghostlibcom_1  |
ghostlibcom_1  | "Please double check your database config."
ghostlibcom_1  |
ghostlibcom_1  | Error ID:
ghostlibcom_1  |     500
ghostlibcom_1  |
ghostlibcom_1  | Error Code:
ghostlibcom_1  |     ENOTFOUND
ghostlibcom_1  |
ghostlibcom_1  | ----------------------------------------
ghostlibcom_1  |
ghostlibcom_1  | DatabaseError: Invalid database host.
ghostlibcom_1  |     at DatabaseStateManager.getState (/var/lib/ghost/versions/4.48.2/core/server/data/db/state-manager.js:64:32)
ghostlibcom_1  |     at DatabaseError.KnexMigrateError (/var/lib/ghost/versions/4.48.2/node_modules/knex-migrator/lib/errors.js:7:26)
ghostlibcom_1  |     at new DatabaseError (/var/lib/ghost/versions/4.48.2/node_modules/knex-migrator/lib/errors.js:55:26)
ghostlibcom_1  |     at /var/lib/ghost/versions/4.48.2/node_modules/knex-migrator/lib/database.js:50:23
ghostlibcom_1  |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
ghostlibcom_1  |     at async DatabaseStateManager.getState (/var/lib/ghost/versions/4.48.2/core/server/data/db/state-manager.js:40:13)
ghostlibcom_1  |     at async DatabaseStateManager.makeReady (/var/lib/ghost/versions/4.48.2/core/server/data/db/state-manager.js:73:25)
ghostlibcom_1  |     at async initDatabase (/var/lib/ghost/versions/4.48.2/core/boot.js:69:5)
ghostlibcom_1  |     at async bootGhost (/var/lib/ghost/versions/4.48.2/core/boot.js:414:9)
ghostlibcom_1  |
ghostlibcom_1  | Error: getaddrinfo ENOTFOUND mariadbrx1.libcom.de
ghostlibcom_1  |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:71:26)
ghostlibcom_1  |
ghostlibcom_1  | [2022-08-19 16:32:44] WARN Ghost is shutting down
ghostlibcom_1  | [2022-08-19 16:32:44] WARN Ghost has shut down
ghostlibcom_1  | [2022-08-19 16:32:44] WARN Your site is now offline
ghostlibcom_1  | [2022-08-19 16:32:44] WARN Ghost was running for a few seconds
```
This is my obfuscated docker-compose.yaml:
```
version: '3.1'

services:
  ghostlibcom:
    image: ghost:4-alpine
    restart: always
    ports:
      - 8080:2368
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: mariadbrx1.libcom.de
      database__connection__port: 3306
      database__connection__user: ghost_libcom
      database__connection__password: Adsfsadfasdfasdfm
      database__connection__database: ghost_libcom
      # this url value is just an example, and is likely wrong for your environment!
      url: https://www.libcom.de
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      #NODE_ENV: development
```
