### ISSUE TITLE
ECONNREFUSED 127.0.0.1:3306 - "Unknown database error" after updating Docker alpine image to latest

### ISSUE THREAD

**Issue by raspberrycoulis** [docker-library/ghost#331]
So, I've been running my three blogs without any issues for the past few years (self hosted on Synology NAS using Docker), but after updating to the latest alpine image, all three blogs shutdown whilst reporting the following issue:

```
[2022-08-22 19:21:29] INFO Ghost is running in production...
[2022-08-22 19:21:29] INFO Your site is now available on https://ghostpi.pro/
[2022-08-22 19:21:29] INFO Ctrl+C to shut down
[2022-08-22 19:21:29] INFO Ghost server started in 1.789s
[2022-08-22 19:21:30] ERROR connect ECONNREFUSED 127.0.0.1:3306
connect ECONNREFUSED 127.0.0.1:3306
"Unknown database error"
Error ID:
    500
Error Code: 
    ECONNREFUSED
----------------------------------------
Error: connect ECONNREFUSED 127.0.0.1:3306
    at /var/lib/ghost/versions/5.10.1/node_modules/knex-migrator/lib/database.js:57:19
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1247:16)
[2022-08-22 19:21:30] WARN Ghost is shutting down
[2022-08-22 19:21:30] WARN Ghost has shut down
[2022-08-22 19:21:30] WARN Your site is now offline
[2022-08-22 19:21:30] WARN Ghost was running for a few seconds
```

This is also mentioned on the [forums](https://forum.ghost.org/t/database-error-upon-deployment-via-docker/32164) but without any solution as of yet.

I've tried reverting to `ghost:5.10.1-alpine` and `ghost:5.10-alpine` images, but the issue persists.

**Comment by tianon** [comment]
See https://github.com/docker-library/ghost/pull/323#issuecomment-1212554428 (temporary solutions are to downgrade to 5.8 or add those environment variables - long term solution is to migrate to MySQL).

**Comment by raspberrycoulis** [comment]
Thanks @tianon - I just found that after digging around various other posts and complaints about the same issue.

**Comment by raspberrycoulis** [comment]
Sorry, but how would I go about migrating to MySQL? I've been running my blogs using the Docker image, so I've not even set the database to anything. Whilst adding the variables to use sqlite3 does fix my issue temporarily, is there a way to migrate my site to MySQL other than starting it in a new container and importing the content again?

**Comment by edrcq** [comment]
I actually have the same issue with 5.14.1-alpine 

The Ghost container cannot connect to the MySQL server. (err 500 etc.. as same as raspberrycoulis)

How can I fix it ?
Why this issue is closed ?

```
version: '3.1'

services:
  ghost:
    image: ghost:5.14.1-alpine
    restart: always
    user: 1003:1003
    ports:
      - 2368:2368
    volumes:
      - ./ghost:/var/lib/ghost/content:rw
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: 
      database__connection__database: ghost
      url: https://altisinfo.com
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 
```

**Comment by raspberrycoulis** [comment]
@edrcq - I ended up migrating to MySQL instead. If you're interested in knowing how, I published [this guide](https://ghostpi.pro/how-to-migrate-sqlite3-to-mysql-for-ghost-v5/) on my Ghost related blog which might be helpful.

**Comment by flpms** [comment]
@raspberrycoulis when I tried to access your blog

![image](https://user-images.githubusercontent.com/4911643/191623056-0fe3a691-d420-4447-be41-2ad43dea01b0.png)

**Comment by raspberrycoulis** [comment]
> @raspberrycoulis when I tried to access your blog
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/4911643/191623056-0fe3a691-d420-4447-be41-2ad43dea01b0.png)

Hmm, odd. What country do you live in? Might be a Cloudflare thing...

**Comment by raspberrycoulis** [comment]
> Brazil, I`ll try run a test with a vpn

Ah, yes. Brazil was on my block list because I noticed quite a few people attempting to do something shady with IP's from Brazil. It should be more lenient now if you wanted to try again.

**Comment by flpms** [comment]
Ouch, people here are easy target for mirroring and attack networks, we are trying to improve our digital education, to avoid that.

Now it's working perfectly, thanks  😊

**Comment by AlexKalopsia** [comment]
Hi, I am having the same issue as reported above. My compose:

```
version: "3.7"
services: 

  ghost:
    container_name: ghost
    image: ghost:latest
    volumes:
      - ./ghost/content:/var/lib/ghost/content
    environment:
      #- url=${BLOG_URL}
      - TZ=${TZ}
      - database__client=mysql
      - database__connection__host=mysql
      - database__connection__user=${MYSQL_USER}
      - database__connection__password=${MYSQL_PSW}
      - database__connection__database=${MYSQL_DB}
    ports:
      - 2368:2368
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    container_name: ghost-db
    image: 'mysql:latest'
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_HOST=172.*.*.*
      - MYSQL_ROOT_PASSWORD=${MYSQL_PSW}
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PSW}
    restart: unless-stopped
```

Any idea? :(
