### ISSUE TITLE
Cannot setup mails on docker

### ISSUE THREAD

**Issue by Mr-KayJayDee** [docker-library/ghost#333]
Hello, i can't setup mails on docker 

```yaml
version: '3.1'
services:
  ghost:
    image: 'ghost:latest'
    restart: always
    ports:
      - '4574:2368'
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: 'XXXXXXX'
      database__connection__database: ghost
      url: 'XXXXXXX'
      mail__transport: SMTP
      mail__options__host: ssl0.ovh.net
      mail__options__port: 465
      mail__options__secureConnection: true
      mail__options__auth__user: XXXXXXX
      mail__options__auth__pass: XXXXXXX
      mail__from: XXXXXXX
  db:
    image: 'mysql:8.0'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: XXXXXXX
```

The ghost app container does not seems to get the mail config either

<img width="384" alt="Screenshot 2022-09-19 at 14 12 28" src="https://user-images.githubusercontent.com/46600662/191014468-eaae05a3-4dc6-4939-969f-d32d200b12ae.png">

Here is the message i get on Ghost itself

![Screenshot 2022-09-19 at 14 12 58](https://user-images.githubusercontent.com/46600662/191014559-a620b83b-bdf8-4cbc-9131-eea21217c981.png)

Thanks for the help, tell me if you need more infos about this 👍🏼
