### ISSUE TITLE
Fresh Install: ERROR Migration lock was never released or currently a migration is running. Migration lock was never released or currently a migration is running.

### ISSUE THREAD

**Issue by mtthidoteu** [docker-library/ghost#337]
Hey!
Every time I install this image I ALWAYS face this issue. I am on a brand new installation with all directories empty and can't figure out why this is happeningl

```
version: '3.1'
services:
  ghost:
    image: ghost
    restart: unless-stopped
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      - database__client=mysql
      - database__connection__host=ghostdb
      - database__connection__user=ghostuser
      - database__connection__password=
      - database__connection__database=ghost
      - url=https://
      - NODE_ENV=production
    networks:
      - default
      - web
    volumes:
      - ./ghost_data:/var/lib/ghost/content
    depends_on:
      - ghostdb

  ghostdb:
    image: lscr.io/linuxserver/mariadb:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_USER=ghostuser
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=ghost
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./db_data:/config
    networks:
      - default


networks:
  default:
  web:
    external: True

```

obviously some elements are censored. I can't figure out what is wrong with my installation!
