### ISSUE TITLE
Sign in and subscription buttons do not function

### ISSUE THREAD

**Issue by tigerkzr** [docker-library/ghost#389]
I spun up a Ghost instance with :latest but the "sign in" and "subscribe" buttons are not functional.  Clicking them has no effect.  The search button does bring up the search bar and the "home" "about" and article links work.

Environment:
```
Ubuntu Server 23.04
Docker 24.0.5
image ghost:latest
traefik reverse proxy
mariadb mysql server
```

- have tried on the latest Chrome and Safari. 
- have tried before and after configuring user in admin console (http://url/ghost)
- have tried both behind reverse proxy and direct host(hostip:hostport)

Of note: On first visit from a browser (ie clean cache) I receive this error:

```
Unknown Request error.

"http://ghost.example.net/favicon.ico"

Error ID:
    b8780970-481d-11ee-afa0-29cbb07008eb

Error Code:
    IMAGE_SIZE_URL

----------------------------------------

Error: connect ECONNREFUSED 10.0.10.31:80
    at /var/lib/ghost/versions/5.60.0/core/server/lib/image/ImageSize.js:192:39
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
```

here are the configuration setting I have setup with env vars:

```
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      # this url value is just an example, and is likely wrong for your environment!
      url: http://ghost.example.net
      # server__host: 0.0.0.0
      # server__port: 2368
      ## database
      database__client: mysql
      database__connection__host: $MARIADB_HOST
      database__connection__user: ghost
      database__connection__password: ghost
      database__connection__database: ghost
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      # NODE_ENV: development
      ## bulk mailer
      mail__transport: smtp
      mail__options__service: mailgun
      mail__options__host: $MAILGUN_SMTP_SERVER
      mail__options__port: $MAILGUN_SMTP_PORT
      mail__options__secure: true
      mail__options__auth__user: $MAILGUN_USER
      mail__options__auth__pass: $MAILGUN_PASSWD
      ## logging
      logging__path: "/logs"
      logging__useLocalTime: true
      logging__level: "info"
      logging__rotation__enabled: true
      logging__rotation__count: 15
      logging__rotation__period: "1d"
      ## image upload
      # imageOptimization_resize: false       #<true>
      ## adapters
      # adapters__storage__active: storage-module-name
      # adapters__storage__storage-module-name__key: value
```

I am at a loss to where else to look to  troubleshoot this, any help or advice is appreciated.
