### ISSUE TITLE
find: /var/lib/ghost/content/themes/source: No such file or directory

### ISSUE THREAD

**Issue by ipari** [docker-library/ghost#395]
The ghost container's status remains "Restarting" after `docker-compose up -d`
When I checked the log, I saw the following: 

```
2023-10-22 02:07:10 find: /var/lib/ghost/content/themes/source: No such file or directory
2023-10-22 02:07:10 find: /var/lib/ghost/content/themes/casper: No such file or directory
```

How can I solve this?

**Comment by LaurentGoderre** [comment]
Can you share your docker compose file? I ran the docker-compose from the readme and didn't get any errors.

**Comment by ipari** [comment]
@LaurentGoderre Thanks for your reply.
Here is my docker-compose.yml

```yaml
version: '3'
services:
    blog:
        image: ghost:5
        restart: always
        ports:
            - 5004:2368
        environment:
            database__client: ${GHOST_DB_CLIENT}
            database__connection__host: ${GHOST_DB_HOST}
            database__connection__user: ${MYSQL_USER}
            database__connection__password: ${MYSQL_PASSWORD}
            database__connection__database: ${MYSQL_DATABASE}
            url: ${GHOST_URL}
        volumes:
            - .content:/var/lib/ghost/content
    db:
        image: mysql:8
        restart: always
        ports:
            - 5005:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes:
            - .db:/var/lib/mysql
```
