### ISSUE TITLE
Can't update site URL

### ISSUE THREAD

**Issue by bsleys** [docker-library/ghost#420]
I'm not sure what I'm doing wrong but no matter what I do I can't get the site URL to update and it continues to point to http://localhost:2368

I've update the URL in the docker compose file but it doesn't change it inside of ghost.  I even tried updating the config.production.json file. Here is my Docker Compose File

```
version: "3.1"
services:
  ghost:
    image: ghost:5-alpine
    restart: always
    ports:
      - 8080:2368
    environment:
      # see https://ghost.org/docs/config/#configuration-options
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: <password removed>
      database__connection__database: ghost
      # this url value is just an example, and is likely wrong for your environment!
      url: https://evergreen-longevity.com
      # contrary to the default mentioned in the linked documentation, this image defaults to NODE_ENV=production (so development mode needs to be explicitly specified if desired)
      NODE_ENV: production
    volumes:
      - /data/ghost:/var/lib/ghost/content
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: <password removed>
    volumes:
      - /data/mysql:/var/lib/mysql
networks: {}
```
