### ISSUE TITLE
tar: /var/lib/ghost/content.orig: Cannot open: No such file or directory 

### ISSUE THREAD

**Issue by twiceyuan** [docker-library/ghost#69]
I use docker compose to create it, the configuration file approximately is:

```
services:
  blog:
    image: "ghost:latest"
    ports:
      - 1984:2368
    volumes:
      - [data directory]:/var/lib/ghost
```

The `data directory` is a new directory and I have full permissions. But it seems failed, the logs show this:

```
tar: /var/lib/ghost/content.orig: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
```

And after this I can see the `content` directory was created in the `data directory`. Is anything wrong?
