### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by maximeag** [docker-library/ghost#89]
Hello everyone,

I would like to use this image through HTTPS, is it possible ? I'm currently using nginx-proxy and docker-letsencrypt-nginx-proxy-companion and I hope there's a way to work with those.

Thank you!

**Comment by SISheogorath** [comment]
It's recommended by the ghost foundation to run ghost behind a reverse proxy. The `ghost-cli` would automatically install a nginx instance when you use the regular setup way.

See: https://docs.ghost.org/docs/cli-install#section-do-you-wish-to-set-up-nginx-

So you are doing everything correctly :)

An alternative to nginx-proxy with docker-letsencrypt-nginx-proxy-companion is [traefik](https://hub.docker.com/_/traefik/) which supports LE out-of-the-box and is perfectly integrated with the docker API.

**Comment by acburdine** [comment]
@maximeag there should be a way to, yeah. Assuming you're using docker-compose (or something similar, the ghost part would be something like:

```yaml
version: '3'
services:
  ghost:
    image: ghost:latest
    environment:
      - VIRTUAL_HOST=yourwebsite.com
      - LETSENCRYPT_HOST=yourwebsite.com
      - url=https://yourwebsite.com # this is used to configure Ghost's url (does need to be lowercase)
  nginx:
    # add nginx config here
  letsencrypt:
    # letsencrypt config
```
Really the only thing unique about that is the `url=https://yourwebsite.com` environment variable - so if you're not using compose just make sure the environment variable is there.


Going to close this as there is a defined way to do this - if you run into any issues with the above approach then feel free to reopen 😄
