### ISSUE TITLE
Haproxy breaks when url env is set

### ISSUE THREAD

**Issue by Sicria** [docker-library/ghost#92]
If I set the ``url`` environment variable via docker-compose and link the container to haproxy, it does not connect. If I leave out the ``url`` environment variable it does connect, but then when you load it up it uses the IP and port as the url.

Docker-compose setup - Works but is broken on the frontend
```
data:
  container_name: data
  image: busybox
  volumes:
    - ../../volumes/ghost-data:/var/lib/ghost/content
haproxy:
  container_name: haproxy
  build: ./haproxy
  links:
    - blog
  ports:
    - "80:80"
    - "443:443"
blog:
  container_name: blog
  image: ghost:alpine
  ports:
    - "2368:2368"
  volumes_from:
    - data
```

Docker-compose setup - Does not connect
```
data:
  container_name: data
  image: busybox
  volumes:
    - ../../volumes/ghost-data:/var/lib/ghost/content
haproxy:
  container_name: haproxy
  build: ./haproxy
  links:
    - blog
  ports:
    - "80:80"
    - "443:443"
blog:
  container_name: blog
  image: ghost:alpine
  environment:
    - url=https://somedomain.com/blog
  ports:
    - "2368:2368"
  volumes_from:
    - data
```

The haproxy setup is the same for both
```
backend bk_blog
    server blog blog:2368 check fall 3 rise 2
```
with an acl for the ``/blog`` directory in the frontend.
```
acl is_blog path_beg /blog


# If this url is for the blog use the blog backend
use_backend bk_blog if is_blog
```

I've tried setting the ``server__host`` & ``server__port`` environment variables but that also does not work.
